# Generated by Django 5.1.5 on 2025-03-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_news_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default='fallback.jpg', null=True, upload_to=''),
        ),
    ]
