# Generated by Django 5.1.5 on 2025-03-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default='fallback.png', null=True, upload_to=''),
        ),
    ]
