# Generated by Django 5.1.5 on 2025-03-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_task_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('tech', 'Công nghệ'), ('sports', 'Thể thao'), ('business', 'Kinh doanh'), ('entertainment', 'Giải trí'), ('other', 'Khác')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='news',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default='fallback.png', null=True, upload_to='news_images/'),
        ),
    ]
