# Generated by Django 5.1.5 on 2025-03-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_news_category_news_updated_alter_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Chưa hoàn thành'), ('completed', 'Đã hoàn thành')], default='pending', max_length=20),
        ),
    ]
